import type { Customer } from "./types"

export const customers: Customer[] = [
  {
    id: "1",
    name: "Olivia Bennett",
    email: "olivia.bennett@northwind.co",
    phone: "+1 (555) 014-2287",
    company: "Northwind Traders",
    status: "Active",
    lastContactDate: "2026-08-21",
  },
  {
    id: "2",
    name: "Marcus Chen",
    email: "m.chen@apexlabs.io",
    phone: "+1 (555) 093-7741",
    company: "Apex Labs",
    status: "Lead",
    lastContactDate: "2026-08-18",
  },
  {
    id: "3",
    name: "Sofia Ramirez",
    email: "sofia.ramirez@brightpath.com",
    phone: "+1 (555) 046-3319",
    company: "Brightpath Consulting",
    status: "Active",
    lastContactDate: "2026-08-20",
  },
  {
    id: "4",
    name: "Liam O'Connor",
    email: "liam.oc@driftwoodhq.ie",
    phone: "+353 (0) 85-014-2233",
    company: "Driftwood HQ",
    status: "Inactive",
    lastContactDate: "2026-06-02",
  },
  {
    id: "5",
    name: "Ava Thompson",
    email: "ava.thompson@lumenworks.com",
    phone: "+1 (555) 078-9065",
    company: "LumenWorks",
    status: "Active",
    lastContactDate: "2026-08-19",
  },
  {
    id: "6",
    name: "Noah Kim",
    email: "noah.kim@quantify.ai",
    phone: "+82 10-5550-1428",
    company: "Quantify AI",
    status: "Lead",
    lastContactDate: "2026-08-11",
  },
  {
    id: "7",
    name: "Emma Fischer",
    email: "e.fischer@alpenhaus.de",
    phone: "+49 151-5550-9921",
    company: "Alpenhaus GmbH",
    status: "Churned",
    lastContactDate: "2026-04-27",
  },
  {
    id: "8",
    name: "Jackson Wright",
    email: "jackson.wright@stonemark.us",
    phone: "+1 (555) 031-6674",
    company: "Stonemark Realty",
    status: "Inactive",
    lastContactDate: "2026-05-30",
  },
]
